#!/bin/bash 

JAVA=$(which java)

if [ ! -x "$JAVA" ]; then
	echo -e "java vm doesn't seem to be installed correctly; please install it in one of these paths:\n${PATH//:/\n}"
	exit 2
fi

VERSION=$($JAVA -version 2>&1)
FULL_VERSION=$(expr match "$VERSION" '.*"\([0-9]*\.[0-9]*\.[0-9_]*\)"')
VERSION=$(expr match "$VERSION" '.*"\([0-9]*\.[0-9]*\)\.[0-9_]*"')


if [[ $VERSION > 1.6 || $VERSION = 1.6 ]]; then
	echo "jCathy is loading..."
	$JAVA -version:"1.6+" -jar jcathy.jar
else
	echo -e "jCathy needs java version >= 1.6 (your version is $FULL_VERSION)"
	exit 1
fi